Button to footer
Fjaereheia/fjaereheia pull request #101
Opened 2024-07-12 09:50 UTC by martinbolle

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
- https://www.notion.so/bekks/Kanban-9d75804e327947458fd2550b89b31775?p=b2bbc649901c431780d2c2af569cf7e9&pm=s
## Beskrivelse.
- Lagt til responsiv knapp for "Kjøp billett" på eventside. Denne tar deg til billettkjøp nederst på siden. 
- Funksjonalitet er ikke helt som oppgaven i notion tilsier, da jeg har hatt problemer med hvordan man kan dytte en "child"-komponent oppover i treet, siden footer ligger i root. 
- Den nye løsningen har da vært å flytte knappen ovenfor footer som et eget element. Dette elementet vises dersom både Eventlabel og Tickets ikke er synlig på siden, og forsvinner dersom en av disse er tilstede. 
- Siden dette ikke er helt avklart har jeg ikke brukt for mye tid på styling.
## Skjermbilder.
![Screenshot 2024-07-12 at 11 48 56](https://github.com/user-attachments/assets/47e7673a-5c9d-4161-8849-0ec72af7a298)
![Screenshot 2024-07-12 at 11 49 51](https://github.com/user-attachments/assets/f3684ddb-1f1b-4741-b159-46c6215b387e)

2024-07-15 06:26 UTC, MichelleGjolberg commented on frontend/app/root.tsx
> +import { useState } from "react";
Fjerne ubrukt import

2024-07-15 12:39 UTC, emilaukner approved these changes
![fancy](https://github.com/user-attachments/assets/16f4ee52-ecf4-4235-88e4-38acbf587cc7)

2024-07-22 11:40 UTC, emilaukner requested changes

2024-07-22 11:40 UTC, emilaukner commented on frontend/app/components/DateTicket.tsx
> +    nb: "Kjøp Billett",
Ble ikke dette fjernet?

2024-07-22 11:40 UTC, emilaukner commented on frontend/app/routes/($lang).event.$id.tsx
> +            <button onClick={handleScroll}>Kjøp</button>
Må være engelsk og norsk

2024-07-22 13:42 UTC, martinbolle commented on frontend/app/components/DateTicket.tsx
> +    nb: "Kjøp Billett",
Det ble fjernet i EventLabels, veit ikke om det ble fjernet her også.

2024-07-23 06:22 UTC, martinbolle commented
> Her tror jeg det har skjedd noe rart
> 
> ![image](https://private-user-images.githubusercontent.com/69513674/351005401-64db7032-69de-4b1e-bb6c-59468895580e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE3MTQ4MzcsIm5iZiI6MTcyMTcxNDUzNywicGF0aCI6Ii82OTUxMzY3NC8zNTEwMDU0MDEtNjRkYjcwMzItNjlkZS00YjFlLWJiNmMtNTk0Njg4OTU1ODBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIzVDA2MDIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2NDVlZTVjYzkxMzhmMjE5NjMxYmQwYTk1YWYwNTVmNDRkNzI0ZGI1ZGM3ODIyMDUzNmExMzczYWY4NWJkMWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xEIZHTpFRPIJPasV6P8EepoUih2IaAM_Sv-DJJr3dnk)

Ser slik ut hos meg:
![Screenshot 2024-07-23 at 08 21 12](https://github.com/user-attachments/assets/c199de76-5629-4eb8-8a00-77e873ce7c2a)

2024-07-23 07:42 UTC, emilaukner approved these changes

2024-07-23 07:57 UTC, merged