Program singelton
Fjaereheia/fjaereheia pull request #121
Opened 2024-07-17 14:26 UTC by MichelleGjolberg

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Lage-en-Programside-singelton-slik-som-infoside-c3f866ab0b9c41258e78c986d270b7f2?pvs=4
## Beskrivelse.
La til program som en singelton, og brukte mye av denne samme stylingen som var 
brukt på event. 
## Skjermbilder.

2024-07-17 14:48 UTC, emilaukner requested changes
Se kommentarer

2024-07-17 14:48 UTC, emilaukner commented on cms/schemaTypes/programpage.ts
> +    }),
Dette burde være RichTextEditor hvis den skal være med

2024-07-17 14:48 UTC, emilaukner commented on frontend/app/routes/($lang).event.$id.tsx
> +
Fjern console log

2024-07-17 14:48 UTC, emilaukner commented on frontend/app/routes/($lang).program._index.tsx
> +  console.log(params);
Fjern console log

2024-07-17 14:48 UTC, emilaukner commented on frontend/app/utils/pageTransition.ts
> +      break;
Dette kommer til å komme i konflikt med #111

2024-07-18 06:02 UTC, annikensyvertsen commented on cms/schemaTypes/programpage.ts
> +    }),
tviler på at vi trenger den i det hele tatt på programside

2024-07-18 07:46 UTC, emilaukner commented on frontend/app/routes/($lang).program._index.tsx
> +          <Link key={index} to={"/event/" + link.slug?.current ?? ""}>
![image](https://github.com/user-attachments/assets/9b1c3c46-2464-4611-ad2c-a8fbfb980876)

Burde endres til `to={link.slug?.current ? "/event/" + link.slug.current : ""}` eller 
`to={link.slug?.current ? "/event/" + link.slug.current : "/event"}`

2024-07-18 09:48 UTC, emilaukner approved these changes

2024-07-18 10:15 UTC, merged