Eventlabel update
Fjaereheia/fjaereheia pull request #129
Opened 2024-07-22 08:03 UTC by martinbolle

## Endringstype.
- Refaktorering.

## Linke til oppgave (Notion).

## Beskrivelse.
Oppdater eventlabels komponent da den ikke var riktig stylet i forhold til resten av elementene på siden.
## Skjermbilder.
![Screenshot 2024-07-22 at 08 42 16](https://github.com/user-attachments/assets/807e62f6-93a9-4b6d-91f2-1eb7e22ee12d)

2024-07-22 09:37 UTC, MichelleGjolberg requested changes
Resolve conflict med main

2024-07-22 09:37 UTC, MichelleGjolberg commented on frontend/app/components/EventLabels.tsx
> +              className="pl-2 p-2 border border-[#F8F8F8] bg-[#F8F8F8] font-bold text-darkBluePrimaryGreenSecondary-primary"
Styling ser bra ut, men dette krasjer med colorcombinations oppdateringen

2024-07-23 07:46 UTC, emilaukner approved these changes

2024-07-23 12:23 UTC, MichelleGjolberg approved these changes
![auroraGif](https://github.com/user-attachments/assets/c32d5b3a-3168-4505-8a9c-9d0ea158c61a)

2024-07-23 12:24 UTC, merged