Refactored eventlabels
Fjaereheia/fjaereheia pull request #132
Opened 2024-07-22 09:40 UTC by annikensyvertsen

## Endringstype.
- Refaktorering.

## Beskrivelse.
Refaktorerte eventlabels kode. Venstrestilte billetter.

## Skjermbilder.
![image](https://github.com/user-attachments/assets/f7c5a4ef-ac4a-4503-8913-05e3fc8d37ab)

2024-07-22 09:50 UTC, emilaukner requested changes

2024-07-22 09:50 UTC, emilaukner commented on frontend/app/components/EventLabels.tsx
> +          })}
Må ha en key, evt index:
`{labels.map((label, index) => {
            return (
              <div  key={index} className={`p-2 border ${textColorBorder} ${textColor}`}>
                {label}
              </div>
            );
          })}`

2024-07-22 09:50 UTC, emilaukner commented on frontend/app/components/EventLabels.tsx
> +          })}
Håndterer heller ikke at label kan være null:
![image](https://github.com/user-attachments/assets/1c5018f3-072e-445c-bfbf-f6fc46b44f24)

2024-07-22 11:53 UTC, emilaukner requested changes

2024-07-22 11:53 UTC, emilaukner commented on frontend/app/components/EventLabels.tsx
> +                  {label}
Må oversette genre hvis engelsk

2024-07-23 11:45 UTC, MichelleGjolberg approved these changes
![catdance](https://github.com/user-attachments/assets/6714ad28-786b-4f6e-a9d2-29eafc8ce0b8)

2024-07-23 12:25 UTC, emilaukner requested changes

2024-07-23 12:25 UTC, emilaukner commented on cms/schema.json
Kjør med enforce required labels, `npx sanity schema extract --enforce-required-fields`

2024-07-24 13:10 UTC, merged