Added status on ticket sale
Fjaereheia/fjaereheia pull request #158
Opened 2024-07-29 08:21 UTC by MichelleGjolberg

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Legge-til-muligheten-til-ha-f-billetter-og-utsolgt-manuelt-i-sanity-9c0bde884d9d45ebbce64b5f87ed9112?pvs=4
## Beskrivelse.
Manuelt legge til statusoppdatering på billettsalg på forestillinger:
- I sanity lagt til mulighet for å velge "ingen bemerkning", "Få igjen" og "Utsolgt" på de forskjellige datoene
- Henter dette ut i frontend, med enkel styling
## Skjermbilder.
![image](https://github.com/user-attachments/assets/956c9207-4873-493c-b2cc-340300539fed)

2024-07-29 08:40 UTC, emilaukner submitted a review, later dismissed

2024-07-29 08:40 UTC, emilaukner commented on cms/schemaTypes/eventType.ts
> +                  {title: 'Få blitter igjen', value: 2},
"Få billetter igjen"

2024-07-29 08:40 UTC, emilaukner commented on cms/schemaTypes/eventType.ts
> +                  {title: 'Ingen bemerkning', value: 1},
Trengs dette hvis feltet ikke er required?

2024-07-29 08:40 UTC, emilaukner commented on frontend/app/components/DateTicket.tsx
> +    nb: "Få igjen!",
Burde dette være "Few tickets left!"/"Få billetter igjen!"?

2024-07-29 10:16 UTC, erlinvan reviewed
Enig i kommentareren til @emilaukner . Ellers ser det bra ut 👍

2024-07-29 10:19 UTC, MichelleGjolberg commented on cms/schemaTypes/eventType.ts
> +                  {title: 'Ingen bemerkning', value: 1},
Tenkte at det var nice siden det er radio buttons (hvis man velger en av de andre, men angrer), vurderte også checkbokser...men da er det fare for at man kan velge flere

2024-07-29 13:35 UTC, erlinvan requested changes

2024-07-29 13:35 UTC, erlinvan commented on cms/schemaTypes/eventType.ts
> +              },
Denne bør vi gjøre required, siden den alltid skal ha en verdi. Det gjør at typene vi opprettet i remix ikke blir nullable, som gjør de enklere å forholde seg til

2024-07-30 06:51 UTC, erlinvan approved these changes

2024-07-30 07:43 UTC, merged