Frontpage remix
Fjaereheia/fjaereheia pull request #18
Opened 2024-06-25 11:24 UTC by martinbolle

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Kanban-9d75804e327947458fd2550b89b31775?p=be5121dbeab54b6285b3ef9666749c31&pm=s
## Beskrivelse.
Lagt til mulighet for å hente data fra forsiden i remix. Også oppdatert .gitignore slik at /build ikke blir med. 
## Skjermbilder.

2024-06-25 13:25 UTC, erlinvan requested changes

2024-06-25 13:25 UTC, erlinvan commented on frontend/app/routes/_index.tsx
> +  return json({title: frontpage.Tittel, ingress: frontpage.Ingress, bilde: frontpage.imageUrl})
Her blandes det en del mellom norske og engelske ord. Kan vi få alt på engelsk her?

2024-06-25 13:25 UTC, erlinvan commented on frontend/app/routes/_index.tsx
> +      <img src={data.bilde} />
Dette dekkes delvis av kommentaren over, men siden `data.bilde` er en url, så bør variabelnavnet også reflektere dette. Noe som data.imageUrl er derfor mer beskrivende

2024-06-26 11:51 UTC, MichelleGjolberg approved these changes

2024-06-26 11:55 UTC, erlinvan approved these changes
Endelig litt remix! 🔥 <img src="https://media2.giphy.com/media/7E5fyVJw6Aoq3G5ogd/giphy.gif"/>

2024-06-26 12:23 UTC, merged