Footer sanity
Fjaereheia/fjaereheia pull request #24
Opened 2024-06-27 06:30 UTC by martinbolle

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Kanban-9d75804e327947458fd2550b89b31775?p=3ad4260033684d44a8c077d040822ad8&pm=s
## Beskrivelse.
Lagt til footer som et egen scheme. Mulig å legge til eksterne lenker og velge ikon for sosiale medie man ønsker.
## Skjermbilder.
- Legg til URL, ikon og knapp for ny fane.
![Screenshot 2024-06-27 at 08 26 34](https://github.com/Fjaereheia/fjaereheia/assets/70632679/37cf972f-7b14-444c-b31c-e538253d4ec0)

- Tekstboks for å legge til link.
![Screenshot 2024-06-27 at 08 27 49](https://github.com/Fjaereheia/fjaereheia/assets/70632679/3b20adbc-6953-4670-bfae-707c61571556)

2024-06-27 10:00 UTC, annikensyvertsen commented on cms/schemaTypes/footerType.ts
Noen spesiell grunn til links består av blokk? og ikke for eksempel of: [ type: 'link'}] ?

2024-06-27 11:36 UTC, erlinvan requested changes

2024-06-27 11:36 UTC, erlinvan commented on cms/schemaTypes/footerType.ts
> +            name: 'links',
Her er formatteringen feil. Bruker du prettier?

2024-06-27 11:36 UTC, erlinvan commented on cms/schemaTypes/footerType.ts
> +    title: 'Bunntekst',
Her tror jeg det engelske ordet footer er mer brukt enn bunntekst, og derfor tenker jeg vi heller bruke det som title

2024-06-27 11:36 UTC, erlinvan commented on cms/sanity.config.ts
> +      S.documentTypeListItem('footer').title('Bunntekst').icon(ArrowDownIcon)
Samme som kommentaren min i footerType. Her tenker jeg vi br bruke Footer

2024-06-27 11:36 UTC, erlinvan commented on cms/sanity.config.ts
> +      S.documentTypeListItem('footer').title('Bunntekst').icon(ArrowDownIcon)
Siden det bare skal eksistere én footer, så bør den også være en singleton. Her kan du se på forsiden for inpirasjon til koden ☺️

2024-06-27 11:41 UTC, annikensyvertsen commented on cms/schemaTypes/footerType.ts
> +                    type: 'block',
Noen spesiell grunn til links består av blokk? og ikke for eksempel of: [ type: 'link'}] ?
Føler det gir mer mening at man kan legge til enkeltstående lenker enn å legge de til i en blokk. Med mindre det er ment at det skal være noe annet i blokken også?

2024-06-28 12:57 UTC, erlinvan approved these changes
<img src="https://media2.giphy.com/media/J1bFxdlD4fWAYIuVjZ/giphy.gif"/>

2024-07-01 13:34 UTC, merged