Seo metadata
Fjaereheia/fjaereheia pull request #51
Opened 2024-07-02 10:52 UTC by MichelleGjolberg

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Legg-til-SEO-description-og-bilder-p-alle-sidetyper-2105afb18fbe449e932dd290ea478a5b?pvs=4

## Beskrivelse.
Lagt til metadata fields på eventType og articleType og lagd en komponent som henter det ut. Har ikke med keywords, grunnet denne posten: https://www.semrush.com/blog/meta-keywords/ 
## Skjermbilder.

2024-07-02 10:53 UTC, MichelleGjolberg commented
+ Lagt til en robots.txt fil - > sett på forskjellige sider og hentet ut det som kan være nødvendig

2024-07-02 12:04 UTC, emilaukner approved these changes
Ser bra ut

2024-07-03 10:08 UTC, erlinvan requested changes

2024-07-03 10:08 UTC, erlinvan commented on cms/schemaTypes/articleType.ts
> +  ],
Vi trenger SEO til forsiden også. Får du lagt det til der og?

2024-07-03 10:08 UTC, erlinvan commented on cms/schemaTypes/articleType.ts
> +      validation: (rule) => [rule.required(), rule.max(160).warning('Maksimalt 160 tegn')],
Kunne man flyttet dette til en egen komponent av noe slag, so vi importerer i filene som trenger SEO data? Da slipper vi å duplisere denne koden for hver side som trenger dette

2024-07-03 10:08 UTC, erlinvan commented on frontend/public/robots.txt
> +Sitemap:https://www.fjareheia.no/sitemap.xml
Denne sitemapen fører ikke til vår applikasjon. Derfor er jeg redd for at denne kan føre til at det blir vanskeligere for søkemotorer å indeksere siden vår. Derfor tenker jeg vi enten må lage en sitemap.xml og så peke på den, eller så kan vi bare fjerne å referere til en sitemap for nå.

Jeg tenker sistnevnte virker som en bra løsning

2024-07-03 10:08 UTC, erlinvan commented on cms/schemaTypes/articleType.ts
> +      title: 'Tittel',
Jeg tror det kan være lurt å bruke "SEO tittle" som tittel her. Dette er for å unngå misforståelser mellom dette feltet og vanlig tittel. Det samme gjelder beskrivelse.

2024-07-04 13:41 UTC, closed without merging