Sticky header
Fjaereheia/fjaereheia pull request #66
Opened 2024-07-04 07:26 UTC by erlinvan

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).

https://www.notion.so/bekks/6b19742d4dff4e659af2d0aab93275d9?v=57a38c17bed64858a5032ac40fe1e11d&p=c88ce0f37dac4b8d82be487a0e5ca36d&pm=s

## Beskrivelse.

Legger til logoen til Bruddet øverst til venstre på alle sider utenom forsiden. Den er nå i svart, noe som gjør at den krasjer ofte med bakgrunnen når den overlapper med innhold. Dette må vi kunne styre på en eller annen måte, for å bedre brukeropplevelsen.

## Skjermbilder.

Eksempler på at den vises
![image](https://github.com/Fjaereheia/fjaereheia/assets/44138705/cef4a36f-d3e3-438e-8be2-16dbe92d7b47)
![image](https://github.com/Fjaereheia/fjaereheia/assets/44138705/0ba72dea-f8b1-4a5b-908a-22a381285a7f)

Vises ikke på forside:
![image](https://github.com/Fjaereheia/fjaereheia/assets/44138705/6e7e2373-5e1c-4b82-b590-7b6cc69a67a1)

2024-07-04 10:34 UTC, erlinvan commented
Usikker på om den skal være sticky eller absoluttposisjonert. Skal avklare dette før eventuell merging

2024-07-04 12:54 UTC, erlinvan commented
Nå overlapper headeren med mye innhold, som gjør at den er litt i veien. Tenker kanskje den kan ventes med å merges

2024-07-05 06:20 UTC, annikensyvertsen commented on frontend/app/components/Header/Header.tsx
> +          <Link to='/' className={location.pathname === "/" ? "active" : ""}>
burde den ikke linke til '/en' hvis man er på engelsk versjon?

2024-07-05 06:22 UTC, annikensyvertsen commented on frontend/app/routes/.info.artikler._index.tsx
> +import { json } from "@remix-run/node";
hvorfor er denne filen med i denne pr-en?

2024-07-05 06:43 UTC, emilaukner requested changes
Se på hvordan logikken i Header reagerer på /en/, ellers bra!

2024-07-05 06:43 UTC, emilaukner commented on frontend/app/components/Header/Header.tsx
> +          <Link to='/' className={location.pathname === "/" ? "active" : ""}>
Ja, headeren dukker opp på frontpage på engelsk også

2024-07-05 07:55 UTC, erlinvan commented on frontend/app/routes/.info.artikler._index.tsx
> +import { json } from "@remix-run/node";
Den ble visst lagt til med uhell. Den er fjernet nå

2024-07-05 08:09 UTC, erlinvan commented on frontend/app/components/Header/Header.tsx
> +          <Link to='/' className={location.pathname === "/" ? "active" : ""}>
Enig! Har fikset det nå

2024-07-05 08:10 UTC, erlinvan commented on frontend/app/components/Header/Header.tsx
> +          <Link to='/' className={location.pathname === "/" ? "active" : ""}>
@emilaukner angeånde kommentaren:
> Ja, headeren dukker opp på frontpage på engelsk også

den dukker opp på `/en/` og f.eks `/denneforsidenfinnesikke` men ikke `/en`. Dette tenker jeg på som korrekt oppførsel, siden det bare er `/en` som skal peke til forsiden på engelsk. Jeg har laget en oppgavae i notion, på å fjerne trailing backslash, for å unngå denne forvirringen. https://www.notion.so/bekks/6b19742d4dff4e659af2d0aab93275d9?v=7531afc97f354149a8cd94eb21b6063d&p=2c74464861a64dbba145134eb8499c48&pm=s

2024-07-05 11:33 UTC, emilaukner approved these changes

2024-07-05 11:59 UTC, merged