Frontpage styling
Fjaereheia/fjaereheia pull request #75
Opened 2024-07-05 11:02 UTC by MichelleGjolberg

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
https://www.notion.so/bekks/Forside-55da32c6e24840eaa8ab1a77bcddfb1d?pvs=4
## Beskrivelse.
Added styling to frontpage both for when there is an event and not, focused on mobile devices. Added svg's in assets map. Added buy tickets button on frontpage
## Skjermbilder.
![image](https://github.com/Fjaereheia/fjaereheia/assets/102430264/6a75f674-e071-4ee0-b1b2-23e505db22a2)
![image](https://github.com/Fjaereheia/fjaereheia/assets/102430264/958d6e80-7edf-4aad-91bf-232f1aff8fc8)
![image](https://github.com/Fjaereheia/fjaereheia/assets/102430264/4a063ef7-f9e1-42e6-a34c-70703b82f5f8)
![image](https://github.com/Fjaereheia/fjaereheia/assets/102430264/34187636-6b3d-4789-85d7-7bc630ef8d17)

2024-07-05 12:49 UTC, emilaukner reviewed
Må tas høyde for #74, ellers veldig bra

2024-07-05 12:49 UTC, emilaukner commented on frontend/app/queries/frontpage-queries.ts
Denne må vel endres til å reflektere endringer som kommer med #74

2024-07-05 12:49 UTC, emilaukner commented on frontend/app/routes/($lang)._index.tsx
> +        <a href={data?.event?.TicketsUrl || ""} target="_blank">
Ref må endres hvis #74 merges

2024-07-05 13:30 UTC, annikensyvertsen commented on frontend/app/routes/($lang)._index.tsx
> +        <a href={data?.event?.TicketsUrl || ""} target="_blank">
Enig.
Mtp at vi vil bort fra link til samleside på ticketmaster (siden det er så kaos der) tenker jeg vi kan linke til event-siden, med et anker ned til billettknappene!

2024-07-08 06:40 UTC, MichelleGjolberg commented on frontend/app/routes/($lang)._index.tsx
> +        <a href={data?.event?.TicketsUrl || ""} target="_blank">
Fikset!

2024-07-08 06:40 UTC, MichelleGjolberg commented on frontend/app/routes/($lang)._index.tsx
> +        <a href={data?.event?.TicketsUrl || ""} target="_blank">
Fikset!

2024-07-08 07:54 UTC, erlinvan requested changes
Veldig fin løsning med SVGene! Eneste jeg tror gjenstår her angår kommentaren min om knappetekst

2024-07-08 08:51 UTC, MichelleGjolberg commented on frontend/app/routes/($lang)._index.tsx
> +        <ButtonLink url="/artikler" buttonText=" &nbsp; &nbsp;Info" />
Prøvde å løse det med en fast bredde og text alignment, for å sentrere innholdet

2024-07-08 10:39 UTC, erlinvan approved these changes

2024-07-08 10:41 UTC, merged