Role list event
Fjaereheia/fjaereheia pull request #77
Opened 2024-07-05 11:05 UTC by emilaukner

## Endringstype.
- Ny funksjonalitet.

## Linke til oppgave (Notion).
[Lenke til Notion](https://www.notion.so/bekks/Legg-til-roller-p-events-9d646c9e8bd4435aae288e0eb537c8ff?pvs=4)

## Beskrivelse.
Lagt til knapp på event som viser roller som er med. Er delt opp i grupper i sanity og vises på forestilling sider i remix.

## Skjermbilder.
Sanity rollegrupper:
![image](https://github.com/Fjaereheia/fjaereheia/assets/69513674/c6873106-6bb1-49fc-a55c-394dcd5845e0)

Remix rollegrupper:
![image](https://github.com/Fjaereheia/fjaereheia/assets/69513674/ad862fd0-1282-4675-aa15-a149929d0af3)
![image](https://github.com/Fjaereheia/fjaereheia/assets/69513674/c29bb096-bb8e-40b4-a0fc-999fe82b4c40)

2024-07-05 13:28 UTC, annikensyvertsen commented
Her er det litt konflikter nå, vil du løse opp i de før review kanskje?

2024-07-08 14:04 UTC, erlinvan requested changes

2024-07-08 14:04 UTC, erlinvan commented on frontend/app/components/RoleDropDown.tsx
> +                  {role.text && <PortableTextComponent textData={role.text} />}
Trenger vi portable text her? Da bør vi nok se på hvordan sørge for at det ikke legges til noen H-tags i portable tekst her, siden de allerede ligge runder en h5. Tror det enkleste er at vi bare tar i mot en string her.

2024-07-09 12:09 UTC, erlinvan approved these changes

2024-07-10 06:04 UTC, merged